project:
  type: book

book:
  title: "Setting up R"
  author: 
    - name: "Nicolas Casajus"
      orcid: "0000-0002-5537-5294"
      url: "https://nicolascasajus.fr"
      affiliations: 
        - name: FRB-CESAB
          url: "https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/"
  date: today
  description: A user guide to set up a working environment for FRB-CESAB training courses<hr>

  favicon: images/favicon.png
  
  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/frbcesab/rsetup/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
  
  reader-mode: false
  search: false
  
  chapters:
    - index.qmd
    - chapters/reproducible-research.qmd
    # - part: "Installation"
    #   chapters:
    #     - chapters/windows.qmd
    #     - chapters/macos.qmd
    #     - chapters/ubuntu.qmd
    # - part: "Configuration"
    #   chapters:
    #     - chapters/rstudio.qmd
    #     - chapters/git.qmd
    #     - chapters/github-ssh.qmd
    #     - chapters/github-token.qmd

format:
  html:
    theme: [cosmo, css/styles.scss]
    code-copy: true
    code-line-numbers: false
    # highlight-style: zenburn
